### ISSUE TITLE
About make reject

### ISSUE THREAD

**Issue by huangxu1991** [RVC-Boss/GPT-SoVITS#950]
https://github.com/RVC-Boss/GPT-SoVITS/blob/4e43f6097fe468cf747237f1088e46b5f4d7724d/GPT_SoVITS/AR/models/utils.py#L212C9-L212C62

may be `process_item_idx = torch.randint(0, 2, size=(1, ))[0]` ? 

Or zero is always expected?

**Comment by huangxu1991** [comment]
@WatchTower-Liu Your sumbit of DPO loss is great! But from the code you submitted, it only repeat NOT CUT! Is it expected?

**Comment by WatchTower-Liu** [comment]
@huangxu1991 right `process_item_idx = torch.randint(0, 1, size=(1, ))[0]` It's just a random choice to decide how to generate reject data. 0 indicates that the first random number is selected.
In order to make use of simple and efficient training, rules are used for ·reject· data generation. Repetition is an obvious problem, so this is used.

**Comment by huangxu1991** [comment]
Thanks for your detailed explanation!
